from enum import StrEnum


class KafkaTopics(StrEnum):
    CONTENT_REQUESTS_TEXT = "CONTENT_REQUESTS_TEXT"
    CONTENT_RESPONSES_TEXT = "CONTENT_RESPONSES_TEXT"
    CONTENT_REQUESTS_JSON = "CONTENT_REQUESTS_JSON"
    CONTENT_RESPONSES_JSON = "CONTENT_RESPONSES_JSON"
    CONTENT_REQUESTS_PICTURE = "CONTENT_REQUESTS_PICTURE"
    CONTENT_RESPONSES_PICTURE = "CONTENT_RESPONSES_PICTURE"
    CONTENT_REQUESTS_DEAD_LETTER = "CONTENT_REQUESTS_DEAD_LETTER"

